//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebAppBasicos_parisina
    {
        public string telanom { get; set; }
        public string color_bar { get; set; }
        public string desc_cliente { get; set; }
        public Nullable<decimal> inv_int_trans { get; set; }
        public Nullable<decimal> rollos_ped_xsurtir { get; set; }
        public Nullable<decimal> rollos_ped_xsurtir_old { get; set; }
        public Nullable<decimal> rollos_ped_surtidos { get; set; }
        public Nullable<decimal> ExistTotal { get; set; }
        public Nullable<decimal> com_sug_tarima { get; set; }
        public Nullable<decimal> sobra_desp_compra { get; set; }
        public Nullable<decimal> faltanteAlmacen { get; set; }
        public Nullable<decimal> faltAlmPedido { get; set; }
        public short max_tarima { get; set; }
        public short preorden_tarima { get; set; }
        public short temporada_tarima { get; set; }
        public short dispo_tarima { get; set; }
        public decimal resurtido_rollos { get; set; }
        public decimal resurtido_mts { get; set; }
        public decimal resurtido_tarima { get; set; }
        public decimal tarima_extra { get; set; }
        public decimal autorizadoXpedido { get; set; }
        public Nullable<decimal> demanda_residual { get; set; }
        public decimal compra_sugerida { get; set; }
        public decimal fabTemporadaTarima { get; set; }
        public decimal fabTemporadaDispo { get; set; }
        public decimal excedentePedido { get; set; }
        public decimal excedenteBodega { get; set; }
        public int skuSinExis { get; set; }
        public int skuBajoDisp { get; set; }
        public int contSku_cve { get; set; }
        public short rollos_tarima { get; set; }
        public decimal rollo_mts { get; set; }
        public System.DateTime fec_ultact { get; set; }
    }
}
