//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BasicosParisinaEntities : DbContext
    {
        public BasicosParisinaEntities()
            : base("name=BasicosParisinaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<xcuser> xcuser { get; set; }
        public virtual DbSet<WebAppBasicos_parisina> WebAppBasicos_parisina { get; set; }
    
        public virtual ObjectResult<WebAppBasicosParisina_Result> WebAppBasicosParisina(string ef_cve, string tipdoc_cve)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var tipdoc_cveParameter = tipdoc_cve != null ?
                new ObjectParameter("tipdoc_cve", tipdoc_cve) :
                new ObjectParameter("tipdoc_cve", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WebAppBasicosParisina_Result>("WebAppBasicosParisina", ef_cveParameter, tipdoc_cveParameter);
        }
    
        public virtual ObjectResult<WebAppInsertaResurdoParisina_Result> WebAppInsertaResurdoParisina(string ef_cve, string tipdoc_cve, string producto, string colorVariante, Nullable<int> autorizar, string id_ultact)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var tipdoc_cveParameter = tipdoc_cve != null ?
                new ObjectParameter("tipdoc_cve", tipdoc_cve) :
                new ObjectParameter("tipdoc_cve", typeof(string));
    
            var productoParameter = producto != null ?
                new ObjectParameter("producto", producto) :
                new ObjectParameter("producto", typeof(string));
    
            var colorVarianteParameter = colorVariante != null ?
                new ObjectParameter("colorVariante", colorVariante) :
                new ObjectParameter("colorVariante", typeof(string));
    
            var autorizarParameter = autorizar.HasValue ?
                new ObjectParameter("autorizar", autorizar) :
                new ObjectParameter("autorizar", typeof(int));
    
            var id_ultactParameter = id_ultact != null ?
                new ObjectParameter("id_ultact", id_ultact) :
                new ObjectParameter("id_ultact", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WebAppInsertaResurdoParisina_Result>("WebAppInsertaResurdoParisina", ef_cveParameter, tipdoc_cveParameter, productoParameter, colorVarianteParameter, autorizarParameter, id_ultactParameter);
        }
    }
}
